[package]
name = "seconds"
version = "0.1.0"
edition = "2021"
authors = ["Thiru T."]

[dependencies]
clap = { version = "4.0.19", features = ["cargo", "derive"] }
regex = "1"

[dev-dependencies]
assert_cmd = "2.0.5"
