[package]
name = "seconds"
version = "1.0.0"
edition = "2021"
authors = ["Thiru T."]

[dependencies]
clap = { version = "4.0.19", features = ["cargo", "derive"] }
regex = "1"

[dev-dependencies]
assert_cmd = "2.0.5"
predicates = "2.1.2"

[profile.release]
codegen-units = 1
lto = true
strip = true

